### Numpy 属性

In [1]:
import numpy as np

array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵

print('number of dim:',array.ndim)  # 维度
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 6

number of dim: 2
shape : (2, 3)
size: 6


### 创建array

In [2]:
a = np.array([2,23,4]) # 1d list
print(a)

a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)

a = np.array([2,23,4],dtype=np.float)
print(a.dtype)

a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

[ 2 23  4]
int32
float64
float32


In [10]:
a = np.array([[2,32,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)
print("\n")

a  = np.zeros((3,4))  # 数据全为0，3行4列
print(a)
print("\n")

a = np.ones((3,4),dtype=np.int) # 数据为1，3行4列
print(a)
print("\n")

a = np.empty((3,4)) # 数据为empty，3行4列,不同环境下输出值不一样。
print(a)

[[ 2 32  4]
 [ 2 32  4]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a = np.arange(10,20,2) # 10-19 的数据，2步长
print(a)
print("\n")

a=np.arange(12).reshape((3,4)) # 3行4列，0-11
a

[10 12 14 16 18]




array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [16]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
a

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

### Numpy基础运算

In [17]:
a = np.array([10,20,30,40])
b = np.arange(4)

In [18]:
c = a - b
print(c)
print("\n")
c = a+b
print(c)
print("\n")
c = a*b
print(c)
print("\n")
c=b**2
print(c)

[10 19 28 37]


[10 21 32 43]


[  0  20  60 120]


[0 1 4 9]


In [20]:
c=10*np.sin(a)  
c
# array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [21]:
print(b<3)  
b
# array([ True,  True,  True, False], dtype=bool)

[ True  True  True False]


array([0, 1, 2, 3])

In [22]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))

print(a)
# array([[1, 1],
#       [0, 1]])

print(b)
# array([[0, 1],
#       [2, 3]])

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [24]:
# Numpy中的两种乘法
# 一是对应元素相乘
# 二是标准的矩阵乘法运算
c_dot = np.dot(a,b)
c_dot_2 = a.dot(b)
c_dot_3 = a*b
print(c_dot)
print(c_dot_2)
print(c_dot_3)

[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
[[0 1]
 [0 3]]


In [31]:
a=np.random.random((2,4)) # 一个random会报错
print(a)

[[0.10849496 0.62849565 0.78154951 0.91686756]
 [0.9317791  0.05134445 0.47539671 0.17043474]]


In [33]:
np.sum(a) 

4.064362675090828

In [34]:
np.min(a)   


0.05134445133039223

In [35]:
np.max(a)

0.9317790963231437

In [36]:
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

# 当axis的值为0的时候，将会以列作为查找单元
# 当axis的值为1的时候，将会以行作为查找单元。
print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

a = [[0.10849496 0.62849565 0.78154951 0.91686756]
 [0.9317791  0.05134445 0.47539671 0.17043474]]
sum = [2.43540767 1.628955  ]
min = [0.10849496 0.05134445 0.47539671 0.17043474]
max = [0.91686756 0.9317791 ]


In [40]:
A = np.arange(2,14).reshape((3,4)) 

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
         
print(np.argmin(A))    # 0,矩阵中最小元素索引
print(np.argmax(A))    # 11,矩阵中最大元素索引

print(np.mean(A))        # 7.5，均值
print(np.average(A))     # 7.5，均值
print(A.mean())
print(np.cumsum(A))     #累加，生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和

print(np.diff(A))    #累差，每一行中后一项与前一项之差

print(np.nonzero(A))    #将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵。

0
11
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [41]:
A = np.arange(14,2, -1).reshape((3,4)) 

# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

print(np.sort(A))     # 每一行排序

# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [42]:
print(np.transpose(A))     # 转置
print(A.T)

# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [43]:
print(A)
# array([[14,13,12,11]
#        [10, 9, 8, 7]
#        [ 6, 5, 4, 3]])

print(np.clip(A,5,9))     # clip(Array,Array_min,Array_max)
# array([[ 9, 9, 9, 9]
#        [ 9, 9, 8, 7]
#        [ 6, 5, 5, 5]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


### Numpy索引

In [44]:
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
         
print(A[3])    # 6

6


In [45]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""
         
print(A[2])         
# [11 12 13 14]

[11 12 13 14]


In [46]:
print(A[1][1])      # 具体值
print(A[1, 1])      # 

8
8


In [47]:
print(A[1, 1:3])    # [8 9]切片这一表示形式即针对第二行中第2到第4列元素进行切片输出（不包含第4列）

[8 9]


In [48]:
for row in A: # 打印，逐行打印
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [49]:
for column in A.T: # 逐列打印
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [51]:
A = np.arange(3,15).reshape((3,4)) 
         
print(A.flatten())   
# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

for item in A.flat: # 迭代输出
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


### Numpy 合并

In [53]:
# vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作。
A = np.array([1,1,1]) # A仅仅是一个拥有3项元素的数组（数列）
B = np.array([2,2,2])
C = np.vstack((A,B))     # vertical stack     
print(C) 
print(A.shape,C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


In [54]:
# 左右合并
D = np.hstack((A,B))       # horizontal stack

print(D)
# [1,1,1,2,2,2]

print(A.shape,D.shape)
# (3,) (6,)

[1 1 1 2 2 2]
(3,) (6,)


In [55]:
# A不是矩阵，无法使用装置。
# 这时需要np.newaxis来操作转置
# 将具有3个元素的array转换为了1行3列以及3行1列的矩阵

print(A[np.newaxis,:]) #变成（1，3）
# [[1 1 1]]

print(A[np.newaxis,:].shape)
# (1,3)

print(A[:,np.newaxis]) # 变成（3，1）
"""
[[1]
[1]
[1]]
"""

print(A[:,np.newaxis].shape)
# (3,1)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [56]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
         
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)
"""
[[1 2]
[1 2]
[1 2]]
"""

print(A.shape,D.shape)
# (3,1) (3,2)

[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


In [58]:
# 合并操作需要针对多个矩阵或序列时
C = np.concatenate((A,B,B,A),axis=0) # axis=0，纵向打印
print(C) 
D = np.concatenate((A,B,B,A),axis=1) # axis=1，按行打印

print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


### Numpy分割

In [60]:
# 等量分割
A = np.arange(12).reshape((3, 4))
print(A)
# 按行操作，从左到右，纵向分割
print(np.split(A,2,axis=1)) #分割为2

# 按列操作，从上到下，横向分割
print(np.split(A,3,axis=0)) #分割为3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [61]:
# 不等量分割
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [62]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))

print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### Numpy copy和deep copy

In [63]:
# "= 的赋值方式会带有关联性
a = np.arange(4)
# array([0, 1, 2, 3])

b = a
c = a
d = b

# 改变a的第一个值，b、c、d的第一个值也会同时改变。



In [64]:
b is a  # True

True

In [65]:
c is a  # True


True

In [66]:
d is a  # True

True

In [67]:
# 同样更改d的值，a、b、c也会改变。
d[1:3] = [22, 33]   # array([0, 22, 33,  3])
print(a)            # array([0, 22, 33,  3])
print(b)            # array([0, 22, 33,  3])
print(c)            # array([0, 22, 33,  3])

[ 0 22 33  3]
[ 0 22 33  3]
[ 0 22 33  3]


In [68]:
# copy() 的赋值方式没有关联性
b = a.copy()
print(b)
a[3]=44
print(a)
print(b)

[ 0 22 33  3]
[ 0 22 33 44]
[ 0 22 33  3]


In [69]:
#如果使用以下
a=[1,2]
b=a[:]
print(b is a)
a[1]=3
print(a)
print(b)

False
[1, 3]
[1, 2]


说明 b 是 a 的复制, 他们拥有不同的内存位置.而 b = a 则是 将a 的指针复制给 b, 所以 a 和 b 索引到了同一个内存位置.

In [71]:
# 但是如果使用numpy，情况就不一样了
a=np.arange(4)
b=a[:]
a[1]=3
print(a)
print(b)
print(a is b)
print("id(a):",id(a))
print("id(b):",id(b))
print("id(a[0]):",id(a[0]))
print("id(b[0]):",id(b[0]))

[0 3 2 3]
[0 3 2 3]
False
id(a): 2886947050480
id(b): 2886947051200
id(a[0]): 2886947058672
id(b[0]): 2886947058672


a,b 的 物理内存id 并不一样，但是 a,b 里面的数据的 id 是一样的, 所以改变 numpy 的 a, b 也跟着改变了。b对a进行了浅复制